package com.corrodinggames.rts.game.units.custom.a;

import android.graphics.PointF;
import com.corrodinggames.rts.game.units.a.t377;
import com.corrodinggames.rts.game.units.a.u378;
import com.corrodinggames.rts.game.units.cg456;
import com.corrodinggames.rts.game.units.custom.aj503;
import com.corrodinggames.rts.game.units.custom.b.g526;
import com.corrodinggames.rts.game.units.custom.bm547;
import com.corrodinggames.rts.game.units.custom.bu555;
import com.corrodinggames.rts.game.units.custom.ca568;
import com.corrodinggames.rts.game.units.custom.ce572;
import com.corrodinggames.rts.game.units.custom.cg574;
import com.corrodinggames.rts.game.units.custom.d.b579;
import com.corrodinggames.rts.game.units.custom.h605;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.UnitReference;
import com.corrodinggames.rts.game.units.custom.o612;
import com.corrodinggames.rts.game.units.custom.u618;
import com.corrodinggames.rts.game.units.custom.v619;
import com.corrodinggames.rts.game.units.custom.z623;
import com.corrodinggames.rts.gameFramework.m.e1216;
import com.corrodinggames.rts.gameFramework.utility.p1351;

/* loaded from: classes.dex */
public final class d489 {
    public aj503 A;
    public LogicBoolean B;
    public aj503 C;
    public LogicBoolean D;
    public aj503 E;
    public LogicBoolean F;
    public LogicBoolean G;
    public v619 H;
    public v619 I;
    public v619 J;
    public boolean Q;
    public bm547[] R;
    public o612 V;
    public Float W;
    public boolean X;
    public boolean Y;
    public boolean Z;
    public int a;
    public int aA;
    public LogicBoolean aB;
    public UnitReference.UnitReferenceOrUnitType aC;
    public boolean aD;
    public boolean aE;
    public LogicBoolean aF;
    public LogicBoolean aH;
    public boolean aI;
    public int aJ;
    public boolean aK;
    public String aL;
    public cg574 aa;
    public u618 ab;
    public Float ad;
    public b579 ae;
    public b579 af;
    public Integer ag;
    public PointF ah;
    public LogicBoolean ai;
    public ca568 aj;
    public int ak;
    public cg456 al;
    public g526 am;
    public LogicBoolean an;
    public LogicBoolean ao;
    public u618 ap;
    public u618 aq;
    public LogicBoolean ar;
    public z623 as;
    public z623 at;
    public ce572 au;
    public ce572 av;
    public ce572 aw;
    public ce572 ax;
    public e1216 ay;
    public e1216 az;
    public String b;
    public String c;
    public aj503 d;
    public UnitReference.UnitReferenceOrUnitType e;
    public UnitReference.UnitReferenceOrUnitType f;
    public UnitReference.UnitReferenceOrUnitType g;
    public bu555 h;
    public aj503 i;
    public String k;
    public v619 l;
    public bm547[] m;
    public boolean n;
    public boolean o;
    public b579 q;
    public b579 r;
    public h605 s;
    public LogicBoolean t;
    public LogicBoolean u;
    public LogicBoolean v;
    public boolean w;
    public boolean x;
    public boolean y;
    public LogicBoolean z;
    public u378 j = u378.popupQueue;
    public float p = -999.0f;
    public boolean K = false;
    public boolean L = false;
    public boolean M = true;
    public boolean N = true;
    public boolean O = false;
    public boolean P = false;
    public float S = 0.01f;
    public boolean T = false;
    public boolean U = false;
    public p1351 ac = new p1351();
    public t377 aG = t377.queueUnit;
    public f491 aM = f491.build;
    public e490 aN = e490.auto;
}
